export const GET_ALL_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const GET_SPECIFIC_PRODUCTS_BY_CATEGORY =
  "GET_SPECIFIC_PRODUCTS_BY_CATEGORY";
